# =======================================#
# -----------DUMBARTON THEME-------------#
# ----------------By: Tyler Butler-------#
#-----------------https://tbutler.org----#
#========================================#

# =======================================#
# -----------BASE SETTINGS---------------#
#========================================#

title: Jiaxin's Homepage
email: jiax.l@outlook.com
description: Explore those unknowns
baseurl:                                       # the subpath of your site, e.g. /blog
url: "https://ljxangus.github.io/"          # the base hostname & protocol for your site, e.g. http://example.com
image: /assets/img/me.jpg               # used to generate site link preview
image_alt: Portrait of LIANG Jiaxin    # image description

# =======================================#
# -----------SITE SETTINGS---------------#
#========================================#: 
author: LIANG Jiaxin
profile_image: /assets/img/me_crop.jpg
occupation: 
snippet:
# twitter: tbutler0x90
github: ljxangus
linkedin: jiaxin-liang-62b69a8a
# stackoverflow: '12935605'
website: https://ljxangus.github.io/
codepen: 
medium: 
email: jiax.l@outlook.com
github_repo: "https://github.com/ljxangus/ljxangus.github.io.git" # 用你的ID替换name
# keybase: tbutler320
pgp: 
ctftime: 
phonenumber: 

#========================================#
# --------- UI THEMES -------------------#
#========================================#
ui_theme: abyss                                 # Create your own theme by setting options in _data/themes.yml


# =======================================#
# -----------BLOG SETTINGS---------------#
#========================================#

tags:  post jekyll styleguide ipsum
twitter-widget: false # true,false                  # Used to show your twitter timeline on blog home page

comments: true                                     # Used to enable comments on blog posts
gitalk_client_id: "f01e267ad6f315eae78d"
gitalk_client_secret: "3ba6c818cacbdcd8d108af4b6cfed500387fc77d"
gitalk_repo: "ljxangus.github.io"
gitalk_owner: "ljxangus"
gitalk_admin: "ljxangus"
gitalk_distraction_mode: false

# =======================================#
# -----------THEME SETTINGS--------------#
#========================================#

nav-color: "#00334e"                                 # options: light, dark, transparent, primary, custom | Change the color of the navbar
footer-color: "#00334e"
color-scheme: "#00334e"                              # options: demo | changes color scheme based on preset values 
card-color: "#00334e"                                # Used on cards like the home highlights section
nav-dIcon: "fas fa-caret-down"                       # Change the navbar dropdown (for mobile or small screen sizes) to any fontawesome icon. for a list of icons visit https://fontawesome.com/ 
animate: true                                        # false or true, uses animate.css to animate certain functions

# =======================================#
# -----------HOME PAGE  SETTINGS --------#
#========================================#
home_option:                                 # options: education, skills, timeline

# =======================================#          # These  settings are for demo purposes only, things like 
# -----------HELP SETTINGS---------------#          #     popup toasts and tooltips designed to help new 
#========================================#          #     developers as they look into using this theme      
help_tips: false                                    # options: true, false  | use false to disable these for production mode


# =======================================#
# -----------BUILD SETTINGS--------------#
#========================================#
theme: 
markdown: kramdown

kramdown:
  syntax_highlighter: rouge

plugins:
  # - jekyll-feed
  # - jekyll-scholar
  - jekyll-environment-variables
sass:
  sass_dir: _sass
  style: compressed


include:
  - _posts

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README_FIRST.md
  - README.md

defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts

# =======================================#
# -----JEKYLL SCHOLAR SETTINGS-----------#
#========================================#
scholar:
  last_name: Liang
  style: ieee
  locale: en
  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib
  replace_strings: true
  join_strings: true
  details_dir: bibliography
  details_layout: bibtex.html
  details_link: 
  query: "@*"

# =======================================#       
# For more information about these settings, visit https://htmlhead.dev #
# ------------META TAG SETTINGS----------#
#========================================#
google-tag: G-D3KXW27WMG
google-site-verification:                         #<meta name="google-site-verification" content="verification_token"><!-- Google Search Console -->
yandex-verification:                              #<meta name="yandex-verification" content="verification_token"><!-- Yandex Webmasters -->
msvalidate:                                       # meta name="msvalidate.01" content="verification_token"><!-- Bing Webmaster Center -->
alexaVerifyID:                                    # <meta name="alexaVerifyID" content="verification_token"><!-- Alexa Console -->
pinterestdomain_verify:                           #<meta name="p:domain_verify" content="code_from_pinterest"><!-- Pinterest Console-->
norton-safeweb:                                   # <meta name="norton-safeweb-site-verification" content="norton_code"><!-- Norton Safe Web -->
detectphone: yes                                  # yes or no. Disable automatic detection and formatting of possible phone numbers 
x-dns-prefetch-control: on                        # on or off. Completely opt out of DNS prefetching by setting to "off"
fbappid:                                          # Facebook OpenGraph 